/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicYahooProxyRouteImport } from './routes/api.public.yahoo-proxy'
import { Route as ApiPublicNseOptionChainRouteImport } from './routes/api.public.nse-option-chain'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYahooProxyRoute = ApiPublicYahooProxyRouteImport.update({
  id: '/api/public/yahoo-proxy',
  path: '/api/public/yahoo-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNseOptionChainRoute = ApiPublicNseOptionChainRouteImport.update({
  id: '/api/public/nse-option-chain',
  path: '/api/public/nse-option-chain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/nse-option-chain': typeof ApiPublicNseOptionChainRoute
  '/api/public/yahoo-proxy': typeof ApiPublicYahooProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/nse-option-chain': typeof ApiPublicNseOptionChainRoute
  '/api/public/yahoo-proxy': typeof ApiPublicYahooProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/nse-option-chain': typeof ApiPublicNseOptionChainRoute
  '/api/public/yahoo-proxy': typeof ApiPublicYahooProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/nse-option-chain' | '/api/public/yahoo-proxy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/nse-option-chain' | '/api/public/yahoo-proxy'
  id:
    | '__root__'
    | '/'
    | '/api/public/nse-option-chain'
    | '/api/public/yahoo-proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicNseOptionChainRoute: typeof ApiPublicNseOptionChainRoute
  ApiPublicYahooProxyRoute: typeof ApiPublicYahooProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/yahoo-proxy': {
      id: '/api/public/yahoo-proxy'
      path: '/api/public/yahoo-proxy'
      fullPath: '/api/public/yahoo-proxy'
      preLoaderRoute: typeof ApiPublicYahooProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nse-option-chain': {
      id: '/api/public/nse-option-chain'
      path: '/api/public/nse-option-chain'
      fullPath: '/api/public/nse-option-chain'
      preLoaderRoute: typeof ApiPublicNseOptionChainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicNseOptionChainRoute: ApiPublicNseOptionChainRoute,
  ApiPublicYahooProxyRoute: ApiPublicYahooProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
