// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



import { decryptKey } from "@/lib/security-utils";

const ENC_URL = "Lz8rIyd1bGQ/KEdBVEYpPzYlITw1ISAsQF1YTmk4KiM1LSI4NnFRXw==";
const ENC_KEY = "IjIVOzYIICIcNnh5Z0wOehE6HTwKJQFqUXN7AA4gLwsCDAlyfTpLekJVdAY2HD0FOS8LHVppX3A9EQwaJwYtAT8FW3kEfyozbDcMCS4oFGoCUWpsdihsCSUscAUqPWVABn8uPDYwOXYwEQAWBHlfcDIpbWc9AwABIwZqYVt5LQ5sHS4WdwU5Bkp+dmc0AjIFYCwAAmUSWHEHey0abx4+CnMFG28cUlZeFjwYNQYlGwo2akAGZVwgIDsqYwoxETk2bV0FUHIINgI8diI/ODV1aQ==";

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    let SUPABASE_URL = process.env.SUPABASE_URL;
    let SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    // Fallback to obfuscated keys if env vars are missing
    if (!SUPABASE_URL || SUPABASE_URL.length < 10) {
      SUPABASE_URL = decryptKey(ENC_URL);
    }
    if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY.length < 10) {
      SUPABASE_PUBLISHABLE_KEY = decryptKey(ENC_KEY);
    }

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      throw new Response(
        'Missing Supabase environment variables.',
        { status: 500 }
      );
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Response('Unauthorized: No request headers available', { status: 401 });
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Response('Unauthorized: No authorization header provided', { status: 401 });
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Response('Unauthorized: Only Bearer tokens are supported', { status: 401 });
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Response('Unauthorized: No token provided', { status: 401 });
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Response('Unauthorized: Invalid token', { status: 401 });
    }

    if (!data.claims.sub) {
      throw new Response('Unauthorized: No user ID found in token', { status: 401 });
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    })
  }
)
