// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Simple XOR + Base64 decryption for public safety obfuscation
function decrypt(enc: string): string {
  const SECRET = "GK_STOCKS_2026";
  try {
    const decoded = atob(enc);
    return decoded.split('').map((char, i) => 
      String.fromCharCode(char.charCodeAt(0) ^ SECRET.charCodeAt(i % SECRET.length))
    ).join('');
  } catch {
    return "";
  }
}

const ENC_URL = "Lz8rIyd1bGQ/KEdBVEYpPzYlITw1ISAsQF1YTmk4KiM1LSI4NnFRXw==";
const ENC_KEY = "IjIVOzYIICIcNnh5Z0wOehE6HTwKJQFqUXN7AA4gLwsCDAlyfTpLekJVdAY2HD0FOS8LHVppX3A9EQwaJwYtAT8FW3kEfyozbDcMCS4oFGoCUWpsdihsCSUscAUqPWVABn8uPDYwOXYwEQAWBHlfcDIpbWc9AwABIwZqYVt5LQ5sHS4WdwU5Bkp+dmc0AjIFYCwAAmUSWHEHey0abx4+CnMFG28cUlZeFjwYNQYlGwo2akAGZVwgIDsqYwoxETk2bV0FUHIINgI8diI/ODV1aQ==";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  let SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || (typeof process !== 'undefined' ? process.env.SUPABASE_URL : undefined);
  let SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || (typeof process !== 'undefined' ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined);

  // If no env var found, use the obfuscated key
  if (!SUPABASE_URL || SUPABASE_URL.length < 10) {
    SUPABASE_URL = decrypt(ENC_URL);
  }
  if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY.length < 10) {
    SUPABASE_PUBLISHABLE_KEY = decrypt(ENC_KEY);
  }

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      'Missing Supabase environment variables.'
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

